version: "1.0.2"

services:
  nodecito:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src
    command: ["npx","nodemon","index.js"]
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_USERNAME: root
      MONGO_INITDB_PASSWORD: 1232
      MONGO_INITDB_DATABASE: data
    volumes:
      - ./data:/data/db
    command: mongod
  
    
